version: '3.1'

services:
  database:
    image: postgres:latest
    command:
      - 'postgres'
      - '-c'
      - 'max_connections=125'
      - '-c'
      - 'shared_buffers=256MB'
    env_file:
      - .env
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - 15432:5432